owner: petebachant
name: clima-local-geometry
title: CliMA LocalGeometry
description: Assessing the impact of a simpler LocalGeometry struct on CUDA
  kernel performance.
git_repo_url: https://github.com/petebachant/clima-local-geometry
questions:
  - What potential speedup could be gained by simplifying the LocalGeometry
    struct in ClimaCore?

environments:
  main:
    kind: julia
    julia: "1.12"
    path: .calkit/envs/main/Project.toml
  clima:
    kind: slurm
    host: clima.gps.caltech.edu

pipeline:
  stages:
    analyze-local-geometry-impact:
      kind: julia-script
      script_path: scripts/analysis_local_geometry_impact.jl
      environment: main
      outputs:
        - path: results/analysis_local_geometry_impact.md
          storage: git

    benchmark-local-geometry-impact:
      kind: sbatch
      environment: clima
      script_path: scripts/run_benchmark_slurm.sh
      inputs:
        - scripts/benchmark_local_geometry_impact.jl
        - ClimaCore.jl/.buildkite/Manifest.toml
        - ClimaCore.jl/src
        - ClimaCore.jl/ext
      sbatch_options:
        - --gpus=1
        - --time=30
      outputs:
        - path: results/benchmark_local_geometry_impact.md
          storage: git
