owner: petebachant
name: clima-local-geometry
title: CliMA LocalGeometry
description: Assessing the impact of a simpler LocalGeometry struct on CUDA
  kernel performance.
git_repo_url: https://github.com/petebachant/clima-local-geometry
questions:
  - What potential speedup could be gained by simplifying the LocalGeometry
    struct in ClimaCore?

environments:
  main:
    kind: julia
    julia: "1.12"
    path: .calkit/envs/main/Project.toml

pipeline:
  stages:
    analyze-local-geometry-impact:
      kind: julia-script
      script_path: scripts/analysis_local_geometry_impact.jl
      environment: main
      outputs:
        - path: results/analysis_local_geometry_impact.md
          storage: git
