owner: petebachant
name: clima-local-geometry
title: CliMA LocalGeometry
description: Assessing the impact of a simpler LocalGeometry struct on
  CUDA kernel performance.
git_repo_url: https://github.com/petebachant/clima-local-geometry
questions:
  - What potential speedup could be gained by simplifying the
    LocalGeometry struct in ClimaCore?

environments:
  main:
    kind: julia
    julia: "1.12"
    path: .calkit/envs/main/Project.toml
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  py:
    kind: uv
    path: .calkit/envs/py/pyproject.toml

pipeline:
  stages:
    sync-atmos-mod-core:
      kind: shell-script
      script_path: scripts/sync-atmos-mod-core.sh
      environment: _system
      inputs:
        - ClimaCore.jl/src
        - ClimaCore.jl/ext
        - ClimaCore.jl/lib
    analyze-local-geometry-impact:
      kind: julia-script
      script_path: scripts/analysis_local_geometry_impact.jl
      environment: main
      outputs:
        - path: results/analysis_local_geometry_impact.md
          storage: git
    # Local geometry impact benchmark
    benchmark-local-geometry-impact:
      kind: sbatch
      environment: clima
      script_path: scripts/run_benchmark_slurm.sh
      inputs:
        - scripts/benchmark_local_geometry_impact.jl
        - ClimaCore.jl/.buildkite/Manifest.toml
        - ClimaCore.jl/src
        - ClimaCore.jl/ext
      sbatch_options:
        - --gpus=1
        - --time=30
      outputs:
        - path: results/benchmark_local_geometry_impact.md
          storage: git
    nsys-baseline:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - --output=results/nsys/baseline
        - julia
        - --project=ClimaAtmos.jl/.buildkite
        - ClimaAtmos.jl/perf/benchmark_step.jl
        - --config_file=config/climaatmos_progedmf_1m.yml
      inputs:
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/src
        - config/climaatmos_progedmf_1m.yml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - path: results/nsys/baseline.nsys-rep
          storage: dvc
        - path: results/nsys/baseline.sqlite
          storage: dvc
    nsys-mod:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - --output=results/nsys/mod
        - julia
        - --project=ClimaAtmos.jl-mod/.buildkite
        - ClimaAtmos.jl-mod/perf/benchmark_step.jl
        - --config_file=config/climaatmos_progedmf_1m.yml
      inputs:
        - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl-mod/src
        - config/climaatmos_progedmf_1m.yml
        - ClimaAtmos.jl-mod/perf/benchmark_step.jl
      outputs:
        - path: results/nsys/mod.nsys-rep
          storage: dvc
        - path: results/nsys/mod.sqlite
          storage: dvc
    compare-kernels:
      kind: jupyter-notebook
      notebook_path: notebooks/compare-kernels.ipynb
      environment: py
      inputs:
        - results/nsys/baseline.sqlite
        - results/nsys/mod.sqlite
      html_storage: git
      executed_ipynb_storage: git
    # Atmos AMIP baseline
    amip-baseline:
      kind: sbatch
      environment: clima
      script_path: scripts/run-julia-script.sh
      args:
        - --project=ClimaAtmos.jl/.buildkite
        - scripts/run_progedmf_1m.jl
      sbatch_options:
        - --gpus=1
        - --time=120
      inputs:
        - config/climaatmos_progedmf_1m.yml
        - scripts/run_progedmf_1m.jl
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/src
    # Atmos AMIP modified
    amip-mod:
      kind: sbatch
      environment: clima
      script_path: scripts/run-julia-script.sh
      args:
        - --project=ClimaAtmos.jl-mod/.buildkite
        - scripts/run_progedmf_1m.jl
      sbatch_options:
        - --gpus=1
        - --time=120
      inputs:
        - config/climaatmos_progedmf_1m.yml
        - scripts/run_progedmf_1m.jl
        - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl-mod/src
    analyze-logs:
      kind: jupyter-notebook
      notebook_path: notebooks/analyze-logs.ipynb
      environment: py
      inputs:
        - from_stage_outputs: amip-baseline
        - from_stage_outputs: amip-mod
      outputs:
        - path: figures/sypd-time-series.png
          storage: git
      html_storage: git
      executed_ipynb_storage: git

notebooks:
  - path: notebooks/analyze-logs.ipynb
    title: Analyze logs
    description: Analyzes the logs from the AMIP baseline and modified runs to
      compare performance metrics and visualize any differences.
    stage: analyze-logs
  - path: notebooks/compare-kernels.ipynb
    title: Compare kernels
    description: Compares the CUDA kernels between the baseline and modified runs
      using the Nsight profiling results to identify any performance differences.
    stage: compare-kernels

figures:
  - path: figures/sypd-time-series.png
    title: SYPD time series
    description:
    stage: analyze-logs
